default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000


development:
  <<: *default
  database: bakesmart_development

test:
  <<: *default
  database: bakesmart_test

production:
  <<: *default
  database: bakesmart_production

